// Generated by tools/export-2x2-rust-moves.mjs. Do not edit manually.
// Source of truth: the vendored cubing.js cube2x2x2 KPuzzle definition.

pub const MOVE_PERM_MAP: [[usize; 8]; 9] = [
    [1usize, 2usize, 3usize, 0usize, 4usize, 5usize, 6usize, 7usize],
    [2usize, 3usize, 0usize, 1usize, 4usize, 5usize, 6usize, 7usize],
    [3usize, 0usize, 1usize, 2usize, 4usize, 5usize, 6usize, 7usize],
    [3usize, 1usize, 2usize, 5usize, 0usize, 4usize, 6usize, 7usize],
    [5usize, 1usize, 2usize, 4usize, 3usize, 0usize, 6usize, 7usize],
    [4usize, 1usize, 2usize, 0usize, 5usize, 3usize, 6usize, 7usize],
    [4usize, 0usize, 2usize, 3usize, 7usize, 5usize, 6usize, 1usize],
    [7usize, 4usize, 2usize, 3usize, 1usize, 5usize, 6usize, 0usize],
    [1usize, 7usize, 2usize, 3usize, 0usize, 5usize, 6usize, 4usize],
];

pub const MOVE_ORI_DELTA: [[u8; 8]; 9] = [
    [0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
    [0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
    [0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
    [1u8, 0u8, 0u8, 2u8, 2u8, 1u8, 0u8, 0u8],
    [0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
    [1u8, 0u8, 0u8, 2u8, 2u8, 1u8, 0u8, 0u8],
    [2u8, 1u8, 0u8, 0u8, 1u8, 0u8, 0u8, 2u8],
    [0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
    [2u8, 1u8, 0u8, 0u8, 1u8, 0u8, 0u8, 2u8],
];
