// Auto-generated by tools/generate-zbll-supplemental-cases.mjs
// Exact-state ZBLL algorithms for legal states absent from the primary dataset.
export const ZBLL_SUPPLEMENTAL_CASES = Object.freeze([
  [
    "ZC:p0,o2,p1,o1,p2,o2,p3,o1|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "U F2 B2 U R2 L2 D F2 U2 F U2 D2 F R2 L2 B U2 F2"
  ],
  [
    "ZC:p0,o0,p1,o0,p2,o2,p3,o1|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "F2 U F2 U' F2 U' F U2 F U2 F' U2 F2 U2 F U2 F'"
  ],
  [
    "ZC:p0,o0,p1,o2,p2,o1,p3,o0|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "R U' L U2 R' U F2 R' F2 R U2 R' F2 R F2 L' U2"
  ],
  [
    "ZC:p0,o2,p1,o1,p2,o0,p3,o0|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "F U' B U2 F' U L2 F' L2 F U2 F' L2 F L2 B' U2"
  ],
  [
    "ZC:p0,o1,p1,o0,p2,o0,p3,o2|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "R2 U R2 U' R2 U' R U2 R U2 R' U2 R2 U2 R U2 R'"
  ],
  [
    "ZC:p0,o1,p1,o1,p3,o2,p2,o2|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "B U2 B2 U' B U F' U2 F U2 B2 U2 B U2 R2 B2 R2 U2"
  ],
  [
    "ZC:p0,o0,p1,o0,p3,o1,p2,o2|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "B2 U' L2 B2 L2 U F U2 F' L2 B2 L2 U2 B' U2 B U2 B'"
  ],
  [
    "ZC:p0,o0,p1,o0,p3,o1,p2,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F U' D F2 U D' F' L2 F L2 B' U2 B D2 B R2 B' D2"
  ],
  [
    "ZC:p0,o0,p1,o0,p3,o1,p2,o2|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "F2 U L2 F2 L2 U' B' U2 B L2 F2 L2 U2 F U2 F' U2 F"
  ],
  [
    "ZC:p0,o0,p1,o0,p3,o2,p2,o1|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "F2 U R2 B2 L2 D B2 R U2 R B2 L' B2 U2 L' U2 L U2"
  ],
  [
    "ZC:p0,o1,p1,o2,p3,o0,p2,o0|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U R2 B2 R F2 R' B2 R F2 R U2"
  ],
  [
    "ZC:p0,o1,p1,o2,p3,o2,p2,o1|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "L2 F2 L2 B U2 B' R2 F R2 U2 F' U B' U2 F2 U' B F'"
  ],
  [
    "ZC:p0,o0,p1,o0,p3,o1,p2,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "U2 R L' U2 R L F L2 B D2 B' L2 U2 F' U2 F' R2 F2"
  ],
  [
    "ZC:p0,o0,p1,o1,p3,o2,p2,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "B' R F2 R' B' D2 R' B2 U2 L2 U2 R' U2 L U2 F2 R2"
  ],
  [
    "ZC:p0,o0,p1,o2,p3,o0,p2,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "B' D' F2 D B' D' F2 R2 U R2 B2 U B2 U' B2 D"
  ],
  [
    "ZC:p0,o1,p1,o0,p3,o2,p2,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F D B2 D' F D B2 R2 U' R2 F2 U' F2 U F2 D'"
  ],
  [
    "ZC:p0,o2,p1,o0,p3,o0,p2,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F R' B2 R F D2 R F2 U2 L2 U2 R U2 L' U2 B2 R2"
  ],
  [
    "ZC:p0,o2,p1,o1,p3,o0,p2,o0|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U B' R2 B' L2 B R2 B' L2 B2"
  ],
  [
    "ZC:p0,o2,p1,o2,p3,o0,p2,o2|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "F' U2 F R2 U2 B2 L2 D2 B' L2 U2 F' U F' U B' F"
  ],
  [
    "ZC:p0,o0,p1,o1,p3,o0,p2,o2|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "R D L2 D' R U2 R2 F2 U' R2 U' B2 R2 U F2"
  ],
  [
    "ZC:p0,o2,p2,o0,p1,o2,p3,o2|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "L' U2 R U2 B2 R2 D2 F2 R' D2 B2 R' U L' U L R'"
  ],
  [
    "ZC:p0,o1,p2,o2,p1,o2,p3,o1|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "R U2 R2 U' R U R F2 R2 F2 R U2 R' U2 F2 R2 F2 U2"
  ],
  [
    "ZC:p0,o0,p2,o0,p1,o1,p3,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "L F' R2 F L D2 F L2 U2 B2 U2 F U2 B' U2 R2 F2"
  ],
  [
    "ZC:p0,o0,p2,o1,p1,o2,p3,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F B U2 L2 F' B L D2 L' F2 L2 B2 U2 R' U2 L F2 L'"
  ],
  [
    "ZC:p0,o0,p2,o2,p1,o0,p3,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "L D R2 D' L D R2 F2 U' F2 L2 U' L2 U L2 D'"
  ],
  [
    "ZC:p0,o1,p2,o1,p1,o0,p3,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F D B' D' F D B R2 U R2 D' L2 D2 R2 B2 D' R2 D' L2"
  ],
  [
    "ZC:p0,o1,p2,o2,p1,o0,p3,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R' F L2 F' R' D2 F' R2 U2 B2 U2 F' U2 B U2 L2 F2"
  ],
  [
    "ZC:p0,o2,p2,o0,p1,o1,p3,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R' D' L2 D R' D' L2 F2 U F2 R2 U R2 U' R2 D"
  ],
  [
    "ZC:p0,o2,p2,o0,p1,o2,p3,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F' D' B D F' D' B' L2 U' L2 D R2 D2 L2 B2 D L2 D R2"
  ],
  [
    "ZC:p0,o0,p2,o1,p1,o2,p3,o0|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "R2 U' B2 R2 B2 U L U2 L' B2 R2 B2 U2 R' U2 R U2 R'"
  ],
  [
    "ZC:p0,o2,p2,o0,p1,o0,p3,o1|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U F2 R2 F L2 F' R2 F L2 F U2"
  ],
  [
    "ZC:p0,o1,p2,o0,p1,o2,p3,o0|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "F D B2 D' F U2 F2 L2 U' F2 U' R2 F2 U L2"
  ],
  [
    "ZC:p0,o2,p2,o2,p1,o1,p3,o1|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "B2 D2 L2 B2 R' B2 R' U2 R F2 R' D F2 D F2 L' F2 R2"
  ],
  [
    "ZC:p0,o1,p2,o0,p1,o0,p3,o2|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U R' F2 R' B2 R F2 R' B2 R2"
  ],
  [
    "ZC:p0,o0,p2,o1,p1,o2,p3,o0|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "L2 U B2 L2 B2 U' R' U2 R B2 L2 B2 U2 L U2 L' U2 L"
  ],
  [
    "ZC:p0,o0,p2,o2,p1,o1,p3,o0|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "L2 U F2 R2 B2 D R2 F U2 F R2 B' R2 U2 B' U2 B U2"
  ],
  [
    "ZC:p0,o0,p2,o2,p3,o1,p1,o0|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "F' L2 F' R2 F L2 F' R2 F2"
  ],
  [
    "ZC:p0,o2,p2,o1,p3,o1,p1,o2|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "R2 F2 R' U R' U R U2 R2 F2 U2 L F2 L' F2 U2 R"
  ],
  [
    "ZC:p0,o0,p2,o0,p3,o1,p1,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "L2 U' L2 U L2 F2 D' B2 D2 R2 D' F D' B2 D F"
  ],
  [
    "ZC:p0,o0,p2,o1,p3,o0,p1,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R D L2 D' R D L2 D2 F2 U F2 R2 D B2 U' B2"
  ],
  [
    "ZC:p0,o1,p2,o0,p3,o2,p1,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "F D B2 D' F L2 F2 R2 B2 U' F2 D' B2 D L2 D' F2"
  ],
  [
    "ZC:p0,o1,p2,o2,p3,o0,p1,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R2 D' B2 D L2 D' R2 U' L2 F2 R2 B2 R D' L2 D R"
  ],
  [
    "ZC:p0,o2,p2,o0,p3,o0,p1,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "U R L' U2 R' L' F L2 F L2 F' L2 U2 B' R2 B' R2 B2"
  ],
  [
    "ZC:p0,o2,p2,o0,p3,o0,p1,o1|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "R2 U R D' L2 D R L2 D B2 U R2 F2 D2 B2 D' L2 D2 F2"
  ],
  [
    "ZC:p0,o1,p2,o0,p3,o0,p1,o2|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "R' U' R' D' R U R' F2 U L2 U' L2 D F2 R2"
  ],
  [
    "ZC:p0,o2,p2,o0,p3,o0,p1,o1|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "R2 U' F' U B2 U' F' U B2 U' F2 R2 D R2 D' F2 U F2 R2"
  ],
  [
    "ZC:p0,o2,p2,o2,p3,o2,p1,o0|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "R' U2 R B2 U2 L2 F2 D2 L' F2 U2 R' U R' U L' R U'"
  ],
  [
    "ZC:p0,o0,p2,o1,p3,o2,p1,o0|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "U2 R2 B2 R F2 R' B2 R F2 R"
  ],
  [
    "ZC:p0,o2,p2,o0,p3,o1,p1,o0|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "B D F2 D' B U2 B2 R2 U' B2 U' L2 B2 U R2 U'"
  ],
  [
    "ZC:p0,o2,p2,o0,p3,o0,p1,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "D F2 R2 U D F' U2 B R2 F2 D2 B' D2 B' D2 F U2"
  ],
  [
    "ZC:p0,o0,p3,o0,p1,o1,p2,o2|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "F2 R2 F L2 F' R2 F L2 F"
  ],
  [
    "ZC:p0,o2,p3,o2,p1,o1,p2,o1|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "B2 R2 B' U B' U R2 F R2 F' U2 B' R2 F' U2 F B"
  ],
  [
    "ZC:p0,o0,p3,o1,p1,o0,p2,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "F' D' B2 D F' D R2 D2 B2 D F2 L2 U' L2 U L2"
  ],
  [
    "ZC:p0,o0,p3,o1,p1,o2,p2,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "B2 U B2 D' R2 F2 U' F2 D2 L2 D' R' D L2 D' R'"
  ],
  [
    "ZC:p0,o0,p3,o2,p1,o2,p2,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "B U B' U B U2 B' F2 L2 U F2 D' F2 D R2 U' R2 L2 F2"
  ],
  [
    "ZC:p0,o1,p3,o0,p1,o1,p2,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "L D R' D' L D R' D2 B2 D L2 U F2 U' F2 D R2 D' F2"
  ],
  [
    "ZC:p0,o1,p3,o2,p1,o0,p2,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "U' F B' U2 F' B' R D2 R F2 R' D2 B2 L' B2 R' B2 L2"
  ],
  [
    "ZC:p0,o2,p3,o0,p1,o0,p2,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "F2 D L2 D' B2 D F2 U B2 R2 F2 L2 F' D B2 D' F'"
  ],
  [
    "ZC:p0,o2,p3,o0,p1,o1,p2,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R' D' L2 D R' B2 R2 F2 L2 U R2 D L2 D' B2 D R2"
  ],
  [
    "ZC:p0,o0,p3,o2,p1,o0,p2,o1|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "L D R2 D' L U2 R2 U R2 U F2 U F2 U R2 L2"
  ],
  [
    "ZC:p0,o2,p3,o1,p1,o1,p2,o2|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "F2 U R2 U' L2 B2 D B D2 B L2 F D2 L2 B L2 D2 F U2"
  ],
  [
    "ZC:p0,o1,p3,o2,p1,o0,p2,o0|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "F U' R2 U R2 U F R2 U L2 U R2 U2 L2 U' F2 L2 U2 L2"
  ],
  [
    "ZC:p0,o0,p3,o0,p1,o2,p2,o1|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "R' F2 R' B2 R F2 R' B2 R2 U2"
  ],
  [
    "ZC:p0,o1,p3,o2,p1,o0,p2,o0|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "F U' R2 U R2 U F U2 R2 D B2 L2 D2 F2 D F2 U B2 R2"
  ],
  [
    "ZC:p0,o2,p3,o1,p1,o0,p2,o0|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "R U2 R F2 R' U2 R U R2 U' F2 U F2 U F2 U' R2 U F2"
  ],
  [
    "ZC:p0,o0,p3,o2,p1,o2,p2,o2|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "B' U2 F U2 R2 F2 D2 L2 F' D2 R2 F' U B' U B F' U"
  ],
  [
    "ZC:p0,o0,p3,o0,p2,o1,p1,o2|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "U B L2 U L2 U F2 R2 D2 F' B' R2 U2 B2 U2 F'"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o1,p1,o2|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "R U B2 L U L' U' F2 R U2 R2 B2 U2 L F2 R2 D2 L' B2"
  ],
  [
    "ZC:p0,o2,p3,o1,p2,o2,p1,o1|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "F' U F R2 U B U' F2 U2 B' R2 U2 R2 F R2 F R2"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o0,p1,o0|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "U F R2 U R2 U F2 L2 D2 F B L2 U2 B2 U2 B'"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o1,p1,o2|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "U R2 U F2 R2 F2 U R D2 L' U2 B2 U2 L D2 R F2 U2"
  ],
  [
    "ZC:p0,o2,p3,o1,p2,o2,p1,o1|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "U R2 U F2 R2 F2 U F2 R2 F R2 F R2 U2 R2 F' R2 F R2"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o1,p1,o2|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "R2 U' F2 B2 D L2 D' F2 R L2 B2 R' F2 D2 F2 L U2 L B2"
  ],
  [
    "ZC:p0,o2,p3,o0,p2,o0,p1,o1|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "R2 U R2 U' R2 U' F' R2 F' D2 F' L2 B2 L2 F D2 F2 R2"
  ],
  [
    "ZC:p0,o2,p3,o1,p2,o2,p1,o1|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "U F2 U R2 F2 R2 U F' D2 B U2 L2 U2 B' D2 F' R2"
  ],
  [
    "ZC:p0,o0,p3,o1,p2,o2,p1,o0|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "L2 U L2 U' L2 U' F' D2 F' U2 F D2 F' L2 F2 L2 U2 F2"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o1,p1,o2|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "F2 U R2 L2 D' B2 D R F2 B2 L' U2 F2 R D2 L2 B2 L B2"
  ],
  [
    "ZC:p0,o2,p3,o1,p2,o2,p1,o1|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "F U R2 B U B' U' R2 U2 F2 R2 F U2 F U2 F2 R2 F"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o1,p1,o2|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "R U B2 L U L' U' L2 D2 L D2 R' D2 R2 D2 B2 L U2"
  ],
  [
    "ZC:p0,o1,p3,o2,p2,o1,p1,o2|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "U R2 U F2 R2 F2 U R' D2 L D2 F2 D2 L' D2 R' F2"
  ],
  [
    "ZC:p1,o1,p0,o2,p2,o0,p3,o0|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "B2 U R2 B2 R2 U' F' U2 F R2 B2 R2 U2 B U2 B' U2 B"
  ],
  [
    "ZC:p1,o2,p0,o1,p2,o0,p3,o0|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "B2 U L2 F2 R2 D F2 U2 R U2 R' U2 B2 R' B2 L U2 L"
  ],
  [
    "ZC:p1,o0,p0,o2,p2,o2,p3,o2|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "B' U2 F U2 R2 F2 D2 L2 F' D2 R2 F' U B' U B F'"
  ],
  [
    "ZC:p1,o2,p0,o2,p2,o1,p3,o1|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "F U2 F2 U' F U F L2 F2 L2 F U2 F' U2 L2 F2 L2 U2"
  ],
  [
    "ZC:p1,o0,p0,o0,p2,o1,p3,o2|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U' R2 B2 R F2 R' B2 R F2 R"
  ],
  [
    "ZC:p1,o0,p0,o1,p2,o0,p3,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F' D' B2 D F' D' B2 L2 U L2 F2 U F2 U' F2 D"
  ],
  [
    "ZC:p1,o0,p0,o1,p2,o2,p3,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "B L' F2 L B D2 L B2 U2 R2 U2 L U2 R' U2 F2 L2"
  ],
  [
    "ZC:p1,o0,p0,o2,p2,o2,p3,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "L' D' R D L' D' R' B2 U' B2 D F2 D2 B2 R2 D B2 D F2"
  ],
  [
    "ZC:p1,o1,p0,o2,p2,o0,p3,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "U2 R L' U2 R' L' F L2 F L2 F' L2 U2 B' R2 B' R2 B2"
  ],
  [
    "ZC:p1,o2,p0,o0,p2,o0,p3,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F' L B2 L' F' D2 L' F2 U2 R2 U2 L' U2 R U2 B2 L2"
  ],
  [
    "ZC:p1,o2,p0,o0,p2,o1,p3,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "B D F2 D' B D F2 L2 U' L2 B2 U' B2 U B2 D'"
  ],
  [
    "ZC:p1,o0,p0,o2,p2,o0,p3,o1|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "L D R2 D' L U2 L2 B2 U' L2 U' F2 L2 U B2"
  ],
  [
    "ZC:p1,o0,p0,o0,p2,o2,p3,o1|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U F' L2 F' R2 F L2 F' R2 F2"
  ],
  [
    "ZC:p1,o1,p0,o2,p2,o0,p3,o0|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "F2 U' R2 F2 R2 U B U2 B' R2 F2 R2 U2 F' U2 F U2 F'"
  ],
  [
    "ZC:p1,o1,p0,o2,p3,o1,p2,o2|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "B2 U R2 F2 L2 D F' D2 F' R2 U2 R2 F D2 F' R2 U2"
  ],
  [
    "ZC:p1,o0,p0,o0,p3,o1,p2,o2|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "L F2 U F2 U R2 B2 D2 R' L' B2 U2 L2 U2 R'"
  ],
  [
    "ZC:p1,o1,p0,o2,p3,o1,p2,o2|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "F2 U R2 F2 R2 U F' D2 B U2 L2 U2 B' D2 F' R2 U2"
  ],
  [
    "ZC:p1,o2,p0,o1,p3,o2,p2,o1|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "R2 U' F2 R2 F2 U' R D2 L' U2 B2 U2 L D2 R F2"
  ],
  [
    "ZC:p1,o2,p0,o1,p3,o2,p2,o1|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "F2 U' R2 B2 L2 D' R2 F2 L' D2 L' F2 U2 F2 L D2 L' F2"
  ],
  [
    "ZC:p1,o1,p0,o2,p3,o1,p2,o2|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "R2 U F2 L2 B2 D F2 R2 B' D2 B' R2 U2 R2 B D2 B' R2"
  ],
  [
    "ZC:p1,o2,p0,o0,p3,o0,p2,o1|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "F R2 U R2 U F2 R2 U2 R2 F2 U2 F U2 F2 U2 F2"
  ],
  [
    "ZC:p1,o2,p0,o1,p3,o2,p2,o1|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "R2 U F2 R2 F2 U R D2 L' U2 B2 U2 L D2 R F2"
  ],
  [
    "ZC:p1,o1,p0,o2,p3,o0,p2,o0|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "R B2 U B2 U R2 F2 D2 R L F2 U2 L2 U2 L'"
  ],
  [
    "ZC:p1,o1,p0,o2,p3,o1,p2,o2|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "B2 U R2 F2 L2 D F D2 F R2 U2 R2 F' D2 F R2"
  ],
  [
    "ZC:p1,o2,p0,o1,p3,o2,p2,o1|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "L2 U' F2 R2 B2 D B2 D2 R F2 L' F2 D2 F2 L F2 R F2"
  ],
  [
    "ZC:p1,o0,p0,o1,p3,o2,p2,o0|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "B L2 U L2 U F2 R2 D2 F' B' R2 U2 B2 U2 F' U2"
  ],
  [
    "ZC:p1,o1,p0,o2,p3,o1,p2,o2|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "F2 U' R2 F2 R2 U' F' D2 B U2 L2 U2 B' D2 F' R2 U2"
  ],
  [
    "ZC:p1,o2,p0,o1,p3,o2,p2,o1|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "F2 U' R2 F2 R2 U' R2 F2 R' F2 R' F2 U2 F2 R F2 R' F2"
  ],
  [
    "ZC:p1,o2,p2,o1,p0,o0,p3,o0|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "L' B2 L' F2 L B2 L' F2 L2"
  ],
  [
    "ZC:p1,o2,p2,o2,p0,o0,p3,o2|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "F' U2 F R2 U2 B2 L2 D2 B' L2 U2 F' U F' U B' F U'"
  ],
  [
    "ZC:p1,o0,p2,o1,p0,o0,p3,o2|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "R D L2 D' R U2 R2 F2 U' R2 U' B2 R2 U F2 U'"
  ],
  [
    "ZC:p1,o0,p2,o0,p0,o1,p3,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "D L2 F2 U D R' F2 R D2 L2 B2 R' B2 R' B2 R U2"
  ],
  [
    "ZC:p1,o1,p2,o1,p0,o2,p3,o2|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "F2 L2 F' U F' U F U2 F2 L2 U2 B L2 B' L2 U2 F"
  ],
  [
    "ZC:p1,o0,p2,o0,p0,o1,p3,o2|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "F2 U F D' B2 D F B2 D R2 U F2 L2 D2 R2 D' B2 D2 L2"
  ],
  [
    "ZC:p1,o1,p2,o2,p0,o2,p3,o1|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "F D B U' B U' D F L2 F' B' U2 F L2 F L2 B' D2 F"
  ],
  [
    "ZC:p1,o0,p2,o0,p0,o1,p3,o2|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "F2 U' L' U R2 U' L' U R2 U' L2 F2 D F2 D' L2 U L2 F2"
  ],
  [
    "ZC:p1,o0,p2,o0,p0,o2,p3,o1|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "R F2 R' B2 R F2 R U R2 U2 B2 U' R2 U2 B2 U B2 R2 U"
  ],
  [
    "ZC:p1,o1,p2,o2,p0,o0,p3,o0|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "U2 F2 R2 F L2 F' R2 F L2 F"
  ],
  [
    "ZC:p1,o0,p2,o0,p0,o1,p3,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "R U' B2 D L' D F2 U2 F2 L' U2 L' F2 U2 L2 D2 B2 R"
  ],
  [
    "ZC:p1,o0,p2,o1,p0,o2,p3,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "B2 U' B2 U B2 L2 D' R2 D2 F2 D' L D' R2 D L"
  ],
  [
    "ZC:p1,o0,p2,o2,p0,o0,p3,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L D R2 D' L B2 L2 F2 R2 U' L2 D' R2 D B2 D' L2"
  ],
  [
    "ZC:p1,o1,p2,o0,p0,o2,p3,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "F D B2 D' F D B2 R2 U' R2 F2 D' L2 U L2 U2"
  ],
  [
    "ZC:p1,o2,p2,o0,p0,o0,p3,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "F2 U' F2 D R2 B2 U B2 L2 D' R' D L2 D' R'"
  ],
  [
    "ZC:p1,o2,p2,o2,p0,o0,p3,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "R' D' L D R' D' L D2 B2 D' R2 U' F2 U F2 D' L2 D F2"
  ],
  [
    "ZC:p1,o2,p2,o1,p3,o0,p0,o0|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "F2 U F2 D' L2 D R2 F2 R D2 R B2 R' D2 R' F2 R2 U2"
  ],
  [
    "ZC:p1,o1,p2,o0,p3,o0,p0,o2|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "L2 U L2 D' B2 D F2 R2 B U2 B R2 B' U2 B' R2 F2 U2"
  ],
  [
    "ZC:p1,o0,p2,o0,p3,o2,p0,o1|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "B2 U B2 D' R2 D R2 F2 R B2 L D2 L' B2 R' F2 R2 U2"
  ],
  [
    "ZC:p1,o0,p2,o0,p3,o0,p0,o0|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U'"
  ],
  [
    "ZC:p1,o0,p2,o2,p3,o1,p0,o0|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "R2 U R2 D' F2 D F2 R2 B R2 F U2 F' R2 B' R2 F2 U2"
  ],
  [
    "ZC:p1,o2,p3,o0,p0,o1,p2,o0|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "R' D' L2 D R' F2 U2 F2 R2 F2 U' B2 U' R2 U F2 B2"
  ],
  [
    "ZC:p1,o0,p3,o2,p0,o1,p2,o0|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U' R' F2 R' B2 R F2 R' B2 R2"
  ],
  [
    "ZC:p1,o2,p3,o1,p0,o1,p2,o2|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "L U2 L2 U' L U R' U2 R U2 L2 U2 L U2 B2 L2 B2"
  ],
  [
    "ZC:p1,o1,p3,o0,p0,o0,p2,o2|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "R2 U F2 L2 B2 D' R2 B D2 B L2 U2 B L2 F' L2 U2 B'"
  ],
  [
    "ZC:p1,o2,p3,o0,p0,o0,p2,o1|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "R2 U B2 R2 B2 U B2 R' U2 R U2 R2 B2 R' U2 R U2 R'"
  ],
  [
    "ZC:p1,o0,p3,o0,p0,o1,p2,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "U B2 U B2 D' R2 F2 U' F2 L2 D R D' L2 D R"
  ],
  [
    "ZC:p1,o0,p3,o1,p0,o0,p2,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "R D L2 D' R D L2 B2 U' B2 R2 D' F2 U F2 U"
  ],
  [
    "ZC:p1,o0,p3,o1,p0,o1,p2,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F' R' L F R L' F' R' F2 R U2 F2 R2 B2 R F2 R' B2 R2"
  ],
  [
    "ZC:p1,o1,p3,o0,p0,o2,p2,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "L' D' R2 D L' D' R2 B2 U B2 L2 D F2 U' F2 U'"
  ],
  [
    "ZC:p1,o1,p3,o2,p0,o0,p2,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "U' B2 U' B2 D L2 F2 U F2 R2 D' L' D R2 D' L'"
  ],
  [
    "ZC:p1,o2,p3,o0,p0,o0,p2,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F B' U2 F B R' D2 R' B2 R D2 F2 L F2 R F2 L2"
  ],
  [
    "ZC:p1,o2,p3,o0,p0,o0,p2,o1|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "L2 U' B2 L2 B2 U' B2 R B2 R F2 R2 U2 L' U2 R' F2 R"
  ],
  [
    "ZC:p1,o0,p3,o1,p0,o2,p2,o0|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U B2 L2 B R2 B' L2 B R2 B"
  ],
  [
    "ZC:p1,o2,p3,o2,p0,o2,p2,o0|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "R' U2 F2 U' L' U F2 R2 B2 D2 L' D2 B2 L2 B2 R' B2 L'"
  ],
  [
    "ZC:p1,o1,p3,o0,p2,o0,p0,o2|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "B' R2 B' L2 B R2 B' L2 B2"
  ],
  [
    "ZC:p1,o0,p3,o1,p2,o2,p0,o0|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "R U' B2 U B2 U R B2 R2 U2 R2 D' R2 D R2 B2 U R2"
  ],
  [
    "ZC:p1,o0,p3,o2,p2,o1,p0,o0|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "F L2 F' R2 F L2 F U F2 U2 R2 U' F2 U2 R2 U R2 F2 U"
  ],
  [
    "ZC:p1,o0,p3,o0,p2,o1,p0,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "L2 U' L2 D F2 R2 U R2 B2 D' F' D B2 D' F'"
  ],
  [
    "ZC:p1,o0,p3,o1,p2,o2,p0,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "F U' R2 D B' D L2 U2 L2 B' U2 B' R2 D2 F2 U2 L2 F"
  ],
  [
    "ZC:p1,o0,p3,o2,p2,o0,p0,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "L D R2 D' L D R2 F2 U' F2 L2 D' B2 U B2 U2"
  ],
  [
    "ZC:p1,o1,p3,o1,p2,o0,p0,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R' U' R U' R' U2 R L2 F2 U' L2 D L2 D' B2 U F2 B2 L2"
  ],
  [
    "ZC:p1,o1,p3,o2,p2,o0,p0,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R2 U' R2 U R2 B2 D' F2 D2 L2 D' B D' F2 D B"
  ],
  [
    "ZC:p1,o2,p3,o0,p2,o1,p0,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R' D' L2 D R' D' L2 F2 U F2 R2 D B2 U' B2"
  ],
  [
    "ZC:p1,o2,p3,o0,p2,o2,p0,o2|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "L' U2 R U2 B2 R2 D2 F2 R' D2 B2 R' U L' U L R' U'"
  ],
  [
    "ZC:p1,o1,p3,o2,p2,o2,p0,o1|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "L2 B2 L' U L' U L U2 L2 B2 U2 R B2 R' B2 U2 L"
  ],
  [
    "ZC:p1,o1,p3,o0,p2,o2,p0,o0|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "F D B2 D' F U2 F2 L2 U' F2 U' R2 F2 U L2 U'"
  ],
  [
    "ZC:p1,o0,p3,o1,p2,o2,p0,o0|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "L2 U L D' R2 D L R2 D F2 U L2 B2 D2 F2 D' R2 D2 B2"
  ],
  [
    "ZC:p1,o2,p3,o0,p2,o0,p0,o1|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "R2 B2 R F2 R' B2 R F2 R U2"
  ],
  [
    "ZC:p1,o2,p3,o2,p2,o1,p0,o1|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "R2 U B2 U' F2 L2 D L D2 L F2 R D2 F2 L F2 D2 R"
  ],
  [
    "ZC:p1,o0,p3,o1,p2,o2,p0,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "D B2 R2 U D F' D2 F' D2 F D2 R2 B U2 B' U2 B2"
  ],
  [
    "ZC:p2,o0,p0,o1,p1,o2,p3,o0|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "L2 F2 L B2 L' F2 L B2 L"
  ],
  [
    "ZC:p2,o2,p0,o2,p1,o2,p3,o0|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "R' U2 R B2 U2 L2 F2 D2 L' F2 U2 R' U R' U L' R U"
  ],
  [
    "ZC:p2,o2,p0,o0,p1,o0,p3,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "D F2 R2 U D F' U2 B R2 F2 D2 B' D2 B' D2 F"
  ],
  [
    "ZC:p2,o2,p0,o0,p1,o1,p3,o0|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "R' D' L2 D R U' F2 R2 D B2 R2 U' R2 D' R2 U2 F2"
  ],
  [
    "ZC:p2,o2,p0,o1,p1,o1,p3,o2|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "R2 F2 R' U R' U F2 R U2 R L2 D2 L' D2 L' F2 R2"
  ],
  [
    "ZC:p2,o0,p0,o2,p1,o1,p3,o0|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "F' L2 F' R2 F L2 F' R2 F2 U2"
  ],
  [
    "ZC:p2,o2,p0,o0,p1,o0,p3,o1|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "R2 U R D' L2 D R L2 U R2 U F2 L2 U2 L2 U F2 U2 R2"
  ],
  [
    "ZC:p2,o1,p0,o0,p1,o0,p3,o2|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "R' U' R' D' R U R' F2 U L2 U' L2 D F2 R2 U2"
  ],
  [
    "ZC:p2,o2,p0,o0,p1,o0,p3,o1|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "L U' F2 U F2 U L U2 F2 D R2 B2 D2 L2 D L2 U R2 F2"
  ],
  [
    "ZC:p2,o0,p0,o0,p1,o1,p3,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L2 D B2 D' R2 D L2 U R2 F2 L2 B2 L' D R2 D' L'"
  ],
  [
    "ZC:p2,o0,p0,o1,p1,o0,p3,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "R D L2 D' R D L2 B2 U' B2 R2 D' F2 U F2"
  ],
  [
    "ZC:p2,o0,p0,o1,p1,o1,p3,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "B D F' D' B D F' D2 R2 D B2 U L2 U' L2 D F2 D' L2"
  ],
  [
    "ZC:p2,o1,p0,o0,p1,o2,p3,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L' D' R2 D L' D F2 D2 R2 D L2 B2 U' B2 U B2"
  ],
  [
    "ZC:p2,o1,p0,o2,p1,o0,p3,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "U2 L2 U' L2 D F2 R2 U R2 B2 D' F' D B2 D' F'"
  ],
  [
    "ZC:p2,o2,p0,o0,p1,o0,p3,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "U' R L' U2 R L F L2 B D2 B' L2 U2 F' U2 F' R2 F2"
  ],
  [
    "ZC:p2,o2,p0,o2,p3,o1,p1,o1|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "B2 L2 D' F2 U L2 U' F' U2 F L2 F' U2 R2 F' L2 B U2 B"
  ],
  [
    "ZC:p2,o0,p0,o1,p3,o2,p1,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F B D2 F B R D2 R' D2 F2 R2 B2 R' U2 R' U2 R"
  ],
  [
    "ZC:p2,o1,p0,o0,p3,o0,p1,o2|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U R' F2 R' B2 R F2 R' B2 R2 U2"
  ],
  [
    "ZC:p2,o0,p0,o1,p3,o2,p1,o0|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "L2 U F2 L2 F2 U F2 R' F2 R U2 L2 F2 R' F2 R U2 L'"
  ],
  [
    "ZC:p2,o0,p0,o2,p3,o1,p1,o0|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "F2 U' R2 F2 R2 U' F2 R2 F U2 F' U2 R2 F' R2 F R2 F'"
  ],
  [
    "ZC:p2,o1,p0,o2,p3,o2,p1,o1|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "R U2 R2 U' R U R F2 R2 F2 R U2 R' U2 F2 R2 F2"
  ],
  [
    "ZC:p2,o0,p0,o0,p3,o1,p1,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "U' F2 U' F2 D R2 B2 U B2 L2 D' R' D L2 D' R'"
  ],
  [
    "ZC:p2,o0,p0,o1,p3,o2,p1,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F B' U2 F' B' R D2 R F2 R' D2 B2 L' B2 R' B2 L2"
  ],
  [
    "ZC:p2,o0,p0,o2,p3,o0,p1,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "L D R2 D' L D R2 F2 U' F2 L2 D' B2 U B2 U"
  ],
  [
    "ZC:p2,o1,p0,o1,p3,o0,p1,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F R B' R B' R F' R' D2 F2 L F2 L' F2 L D2 B2 R2 U2"
  ],
  [
    "ZC:p2,o1,p0,o2,p3,o0,p1,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "U F2 U F2 D' L2 B2 U' B2 R2 D L D' R2 D L"
  ],
  [
    "ZC:p2,o2,p0,o0,p3,o1,p1,o0|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "R' D' L2 D R' D' L2 F2 U F2 R2 D B2 U' B2 U'"
  ],
  [
    "ZC:p2,o2,p0,o0,p3,o2,p1,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "F' L' B L' B L' F L D2 F2 R' F2 R F2 R' D2 B2 L2 U2"
  ],
  [
    "ZC:p2,o2,p0,o0,p3,o2,p1,o2|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "L' U2 F2 D' L' D F2 U2 L' B2 R2 D2 R D2 R B2 L2 U2"
  ],
  [
    "ZC:p2,o2,p0,o0,p3,o0,p1,o1|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U F2 R2 F L2 F' R2 F L2 F"
  ],
  [
    "ZC:p2,o1,p0,o0,p3,o2,p1,o0|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "F D B2 D' F U2 F2 L2 U' F2 U' R2 F2 U L2 U2"
  ],
  [
    "ZC:p2,o0,p0,o1,p3,o2,p1,o0|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "R2 U' F2 R2 F2 U' F2 R U2 R' U2 R2 F2 R U2 R' U2 R"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o1,p3,o2|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "R U B2 L U L' U' L2 D2 L D2 R' D2 R2 D2 B2 L"
  ],
  [
    "ZC:p2,o0,p1,o1,p0,o2,p3,o0|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "L2 U L2 U' L2 U' F' L2 U2 F2 L2 U2 F' U2 F' U2 L2 F'"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o1,p3,o2|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "F2 U R2 L2 D' B2 D R F2 R B2 L' U2 F2 R D2 L' U2 R'"
  ],
  [
    "ZC:p2,o2,p1,o1,p0,o2,p3,o1|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "F U R2 B U B' U' R2 U2 F2 R2 F U2 F U2 F2 R2 F U2"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o1,p3,o2|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "U R2 U F2 R2 F2 U R' D2 L D2 F2 D2 L' D2 R' F2 U2"
  ],
  [
    "ZC:p2,o2,p1,o1,p0,o2,p3,o1|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "F U R2 B U B' U' B2 D2 B D2 F' D2 F2 D2 R2 B U2"
  ],
  [
    "ZC:p2,o0,p1,o0,p0,o1,p3,o2|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "U B L2 U L2 U F2 R2 D2 F' B' R2 U2 B2 U2 F' U2"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o1,p3,o2|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "R U B2 L U L' U' B2 U2 R2 B2 R U2 R U2 R2 B2 R"
  ],
  [
    "ZC:p2,o2,p1,o1,p0,o2,p3,o1|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "F2 U' R2 L2 D B2 D' R2 F R2 F L2 U2 L2 B' D2 F2 B L2"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o1,p3,o2|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "R' U R F2 D R D B2 L' D2 F2 D2 R D2 F2 R2 L F2"
  ],
  [
    "ZC:p2,o2,p1,o0,p0,o0,p3,o1|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "R2 U R2 U' R2 U' F' U2 L2 B2 U2 L2 F' D2 F' R2 D2 F'"
  ],
  [
    "ZC:p2,o2,p1,o1,p0,o2,p3,o1|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "U F2 U R2 F2 R2 U F' D2 B U2 L2 U2 B' D2 F' R2 U2"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o0,p3,o0|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "U F R2 U R2 U F2 R2 U2 R2 F2 U2 F U2 F2 U2 F2"
  ],
  [
    "ZC:p2,o1,p1,o2,p0,o1,p3,o2|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "U R2 U F2 R2 F2 U R D2 L' U2 B2 U2 L D2 R F2"
  ],
  [
    "ZC:p2,o2,p1,o1,p0,o2,p3,o1|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "U R2 U F2 L2 B2 D F2 R2 B' D2 B' R2 U2 R2 B D2 B' R2"
  ],
  [
    "ZC:p2,o0,p1,o0,p3,o2,p0,o1|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "R' F2 R' B2 R F2 R' B2 R2"
  ],
  [
    "ZC:p2,o1,p1,o2,p3,o0,p0,o0|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "B2 U B D' F2 D B F2 D L2 U B2 R2 D2 L2 D' F2 D2 R2"
  ],
  [
    "ZC:p2,o1,p1,o2,p3,o0,p0,o0|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "F U' R2 U R2 U F R2 F2 U2 F2 D' F2 D F2 R2 U F2"
  ],
  [
    "ZC:p2,o2,p1,o1,p3,o0,p0,o0|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "R D2 L' U2 L D2 R U' R2 U B2 D' F2 D B2 U R2 U' R2"
  ],
  [
    "ZC:p2,o0,p1,o2,p3,o2,p0,o2|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "B' U2 F U2 R2 F2 D2 L2 F' D2 R2 F' U B' U B F' U'"
  ],
  [
    "ZC:p2,o2,p1,o2,p3,o1,p0,o1|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "B2 R2 B' U B' U B U2 B2 R2 U2 F R2 F' R2 U2 B"
  ],
  [
    "ZC:p2,o0,p1,o0,p3,o1,p0,o2|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "F2 R2 F L2 F' R2 F L2 F U2"
  ],
  [
    "ZC:p2,o0,p1,o2,p3,o0,p0,o1|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "L D R2 D' L U2 L2 B2 U' L2 U' F2 L2 U B2 U'"
  ],
  [
    "ZC:p2,o2,p1,o1,p3,o1,p0,o2|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "F2 U R2 U' L2 B2 D B D2 B L2 F D2 L2 B L2 D2 F"
  ],
  [
    "ZC:p2,o0,p1,o1,p3,o0,p0,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "R D L2 D' R F2 R2 B2 L2 U' R2 D' L2 D F2 D' R2"
  ],
  [
    "ZC:p2,o0,p1,o1,p3,o2,p0,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "B2 U' B2 D L2 F2 U F2 R2 D' L' D R2 D' L'"
  ],
  [
    "ZC:p2,o0,p1,o2,p3,o2,p0,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L' D' R D L' D' R D2 F2 D' L2 U' B2 U B2 D' R2 D B2"
  ],
  [
    "ZC:p2,o1,p1,o0,p3,o1,p0,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "F' U' F U' F' U2 F B2 L2 U' B2 D B2 D' R2 U R2 L2 B2"
  ],
  [
    "ZC:p2,o1,p1,o2,p3,o0,p0,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "U F B' U2 F B R' D2 R' B2 R D2 F2 L F2 R F2 L2"
  ],
  [
    "ZC:p2,o2,p1,o0,p3,o0,p0,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "F2 U' F2 U F2 R2 D' L2 D2 B2 D' R D' L2 D R"
  ],
  [
    "ZC:p2,o2,p1,o0,p3,o1,p0,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "B D F2 D' B D F2 D2 R2 U R2 B2 D L2 U' L2"
  ],
  [
    "ZC:p2,o0,p3,o2,p0,o1,p1,o0|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "R U' L U2 R' U F2 R' F2 R U2 R' F2 R F2 L'"
  ],
  [
    "ZC:p2,o2,p3,o1,p0,o0,p1,o0|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "F U' B U2 F' U L2 F' L2 F U2 F' L2 F L2 B'"
  ],
  [
    "ZC:p2,o1,p3,o0,p0,o0,p1,o2|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "R2 U R2 U' R2 U R' U2 F2 R' U2 L' U2 B2 R B2 L F2"
  ],
  [
    "ZC:p2,o0,p3,o0,p0,o2,p1,o1|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "F2 U F2 U' F2 U F' U2 L2 F' U2 B' U2 R2 F R2 B L2"
  ],
  [
    "ZC:p2,o0,p3,o0,p0,o0,p1,o0|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "U2"
  ],
  [
    "ZC:p2,o2,p3,o1,p0,o2,p1,o1|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "U F2 B2 U R2 L2 D F2 U2 F U2 D2 F R2 L2 B U2 F2 U2"
  ],
  [
    "ZC:p2,o0,p3,o0,p1,o1,p0,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R L' U2 R' L' F L2 F L2 F' L2 U2 B' R2 B' R2 B2"
  ],
  [
    "ZC:p2,o0,p3,o1,p1,o2,p0,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "U R2 U R2 D' F2 L2 U' L2 B2 D F D' B2 D F"
  ],
  [
    "ZC:p2,o0,p3,o2,p1,o0,p0,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "B' D' F2 D B' D' F2 R2 U R2 B2 D L2 U' L2 U'"
  ],
  [
    "ZC:p2,o1,p3,o0,p1,o2,p0,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F D B2 D' F D B2 R2 U' R2 F2 D' L2 U L2 U"
  ],
  [
    "ZC:p2,o2,p3,o0,p1,o0,p0,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "U' R2 U' R2 D B2 L2 U L2 F2 D' B' D F2 D' B'"
  ],
  [
    "ZC:p2,o2,p3,o2,p1,o0,p0,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R' F' L F' L F' R F D2 R2 B' R2 B R2 B' D2 L2 F2 U2"
  ],
  [
    "ZC:p2,o0,p3,o1,p1,o0,p0,o2|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "R D L2 D' R U2 R2 F2 U' R2 U' B2 R2 U F2 U2"
  ],
  [
    "ZC:p2,o2,p3,o1,p1,o0,p0,o0|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U' F' L2 F' R2 F L2 F' R2 F2"
  ],
  [
    "ZC:p2,o2,p3,o2,p1,o0,p0,o2|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "F' U2 R2 D' F' D R2 U2 F' L2 B2 D2 B D2 B L2 F2 U2"
  ],
  [
    "ZC:p2,o0,p3,o0,p1,o1,p0,o2|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "B2 U' R2 B2 R2 U' R2 F R2 F L2 F2 U2 B' U2 F' L2 F"
  ],
  [
    "ZC:p2,o0,p3,o0,p1,o1,p0,o2|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "R L D2 R L F L2 F' D2 R2 B2 L2 B' U2 F' L2 F"
  ],
  [
    "ZC:p2,o1,p3,o1,p1,o2,p0,o2|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "B U2 B2 U' B U F' U2 F U2 B2 U2 B U2 R2 B2 R2"
  ],
  [
    "ZC:p2,o1,p3,o2,p1,o0,p0,o0|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U R2 B2 R F2 R' B2 R F2 R"
  ],
  [
    "ZC:p2,o0,p3,o0,p1,o1,p0,o2|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "F2 U R2 F2 R2 U R2 F' U2 F U2 F2 R2 F' U2 F U2 F'"
  ],
  [
    "ZC:p2,o0,p3,o0,p1,o2,p0,o1|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "R2 U' F2 R2 F2 U' R2 F2 R' U2 R U2 F2 R F2 R' F2 R"
  ],
  [
    "ZC:p3,o0,p0,o2,p1,o1,p2,o0|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "R2 U R2 D' F2 D F2 R2 B R2 F U2 F' R2 B' R2 F2"
  ],
  [
    "ZC:p3,o1,p0,o0,p1,o0,p2,o2|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "L2 U L2 D' B2 D F2 R2 B U2 B R2 B' U2 B' R2 F2"
  ],
  [
    "ZC:p3,o2,p0,o1,p1,o0,p2,o0|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "F2 U F2 D' L2 D R2 F2 R D2 R B2 R' D2 R' F2 R2"
  ],
  [
    "ZC:p3,o0,p0,o0,p1,o0,p2,o0|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U"
  ],
  [
    "ZC:p3,o0,p0,o0,p1,o2,p2,o1|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "B2 U B2 D' R2 D R2 F2 R B2 L D2 L' B2 R' F2 R2"
  ],
  [
    "ZC:p3,o1,p0,o2,p2,o0,p1,o0|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "B2 L2 B R2 B' L2 B R2 B"
  ],
  [
    "ZC:p3,o1,p0,o2,p2,o2,p1,o1|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "F D B U' B' U D' F' R2 F R2 B' R2 F' R2 B2 U2 B'"
  ],
  [
    "ZC:p3,o0,p0,o0,p2,o1,p1,o2|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "B U' L2 U L2 U B U2 L2 D F2 R2 D2 B2 D B2 U F2 L2"
  ],
  [
    "ZC:p3,o0,p0,o0,p2,o2,p1,o1|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "R F2 R' B2 R F2 R U R2 U2 B2 U B2 D2 L2 D' L2 B2 D'"
  ],
  [
    "ZC:p3,o0,p0,o0,p2,o1,p1,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "R U' B2 D L' D L' U2 F2 L' F2 U2 L' D2 B2 R U2 R"
  ],
  [
    "ZC:p3,o0,p0,o1,p2,o2,p1,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "B2 U B2 D' R2 F2 U' F2 L2 D R D' L2 D R"
  ],
  [
    "ZC:p3,o0,p0,o2,p2,o0,p1,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "B' D' F2 D B' D L2 D2 F2 D B2 R2 U' R2 U R2"
  ],
  [
    "ZC:p3,o1,p0,o0,p2,o2,p1,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "F D B2 D' F D B2 R2 U' R2 F2 D' L2 U L2"
  ],
  [
    "ZC:p3,o2,p0,o0,p2,o0,p1,o1|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "U2 B2 U' B2 D L2 F2 U F2 R2 D' L' D R2 D' L'"
  ],
  [
    "ZC:p3,o2,p0,o2,p2,o0,p1,o2|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "F U F' U F U2 F' B2 R2 U B2 D' B2 D L2 U' R2 L2 B2"
  ],
  [
    "ZC:p3,o2,p0,o2,p2,o0,p1,o2|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "F' U2 F R2 U2 B2 L2 D2 B' L2 U2 F' U F' U B' F U"
  ],
  [
    "ZC:p3,o0,p0,o1,p2,o0,p1,o2|ZE:p2,o0,p1,o0,p3,o0,p0,o0",
    "R D L2 D' R U2 R2 F2 U' R2 U' B2 R2 U F2 U"
  ],
  [
    "ZC:p3,o2,p0,o1,p2,o0,p1,o0|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "U2 R' F2 R' B2 R F2 R' B2 R2"
  ],
  [
    "ZC:p3,o1,p0,o1,p2,o2,p1,o2|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "F2 L2 F' U F' U L2 F U2 F B2 D2 B' D2 B' L2 F2"
  ],
  [
    "ZC:p3,o0,p0,o0,p2,o1,p1,o2|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "F2 U F D' B2 D F B2 U F2 U L2 B2 U2 B2 U L2 U2 F2"
  ],
  [
    "ZC:p3,o2,p1,o0,p0,o0,p2,o1|ZE:p0,o0,p1,o0,p2,o0,p3,o0",
    "R2 B2 R F2 R' B2 R F2 R"
  ],
  [
    "ZC:p3,o1,p1,o0,p0,o2,p2,o0|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "F D B2 D' F U2 F2 D R2 U R2 B2 D' R2 U' R2"
  ],
  [
    "ZC:p3,o0,p1,o1,p0,o2,p2,o0|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "R U' B2 U B2 U R B2 U F2 U B2 U2 F2 U' R2 F2 U2 F2"
  ],
  [
    "ZC:p3,o0,p1,o1,p0,o2,p2,o0|ZE:p1,o0,p0,o0,p3,o0,p2,o0",
    "D B2 L2 U D F' L2 F D2 B2 R2 F' R2 F' R2 F"
  ],
  [
    "ZC:p3,o0,p1,o1,p0,o2,p2,o0|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "R U' B2 U B2 U R U2 B2 D L2 F2 D2 R2 D R2 U L2 B2"
  ],
  [
    "ZC:p3,o0,p1,o2,p0,o1,p2,o0|ZE:p2,o0,p0,o0,p1,o0,p3,o0",
    "R U R D R' U' R B2 U2 L2 U' B2 R2 U L2 D L2 D2 F2"
  ],
  [
    "ZC:p3,o1,p1,o0,p0,o0,p2,o2|ZE:p2,o0,p3,o0,p0,o0,p1,o0",
    "U2 F' L2 F' R2 F L2 F' R2 F2"
  ],
  [
    "ZC:p3,o2,p1,o0,p0,o2,p2,o2|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "L' U2 R U2 B2 R2 D2 F2 R' D2 B2 R' U L' U L R' U"
  ],
  [
    "ZC:p3,o1,p1,o2,p0,o2,p2,o1|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "L2 B2 L' U L' U B2 R B2 R' U2 L' B2 R' U2 R L"
  ],
  [
    "ZC:p3,o0,p1,o0,p0,o1,p2,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L2 U L2 D' B2 R2 U' R2 D2 F2 D' B' D F2 D' B'"
  ],
  [
    "ZC:p3,o0,p1,o1,p0,o2,p2,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "F U' R2 D B' D B' U2 L2 B' L2 U2 B' D2 R2 F U2 F"
  ],
  [
    "ZC:p3,o0,p1,o2,p0,o0,p2,o1|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L D R2 D' L D R2 F2 U' F2 L2 D' B2 U B2"
  ],
  [
    "ZC:p3,o1,p1,o2,p0,o0,p2,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "R2 D F2 D' L2 D R2 U L2 B2 R2 F2 R' D L2 D' R'"
  ],
  [
    "ZC:p3,o2,p1,o0,p0,o1,p2,o0|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "R' D' L2 D R' D B2 D2 L2 D R2 F2 U' F2 U F2"
  ],
  [
    "ZC:p3,o2,p1,o0,p0,o2,p2,o2|ZE:p3,o0,p2,o0,p1,o0,p0,o0",
    "L U L' U L U2 L' R2 F2 U R2 D' R2 D B2 U' F2 B2 R2"
  ],
  [
    "ZC:p3,o2,p1,o0,p2,o0,p0,o1|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "L2 U' F2 L2 F2 U R U2 R' F2 L2 F2 U2 L' U2 L U2 L'"
  ],
  [
    "ZC:p3,o1,p1,o0,p2,o0,p0,o2|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "R2 U B2 L2 F2 D L2 U2 F U2 F' U2 R2 F' R2 B U2 B"
  ],
  [
    "ZC:p3,o2,p1,o0,p2,o0,p0,o1|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "R2 U F2 R2 F2 U' L' U2 L F2 R2 F2 U2 R U2 R' U2 R"
  ],
  [
    "ZC:p3,o0,p1,o0,p2,o1,p0,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "L' B R2 B' L' D2 B' L2 U2 F2 U2 B' U2 F U2 R2 B2"
  ],
  [
    "ZC:p3,o0,p1,o1,p2,o0,p0,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R D L2 D' R D L2 B2 U' B2 R2 U' R2 U R2 D'"
  ],
  [
    "ZC:p3,o0,p1,o1,p2,o1,p0,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "B D F' D' B D F L2 U L2 D' R2 D2 L2 F2 D' L2 D' R2"
  ],
  [
    "ZC:p3,o1,p1,o0,p2,o2,p0,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "L' D' R2 D L' D' R2 B2 U B2 L2 U L2 U' L2 D"
  ],
  [
    "ZC:p3,o1,p1,o2,p2,o0,p0,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R B' L2 B R D2 B R2 U2 F2 U2 B U2 F' U2 L2 B2"
  ],
  [
    "ZC:p3,o2,p1,o0,p2,o0,p0,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F B U2 R2 F B' R D2 R' B2 R2 F2 U2 L' U2 R B2 R'"
  ],
  [
    "ZC:p3,o2,p1,o2,p2,o2,p0,o0|ZE:p1,o0,p0,o0,p2,o0,p3,o0",
    "R' U2 R B2 U2 L2 F2 D2 L' F2 U2 R' U R' U L' R"
  ],
  [
    "ZC:p3,o0,p1,o1,p2,o2,p0,o0|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U' F2 R2 F L2 F' R2 F L2 F"
  ],
  [
    "ZC:p3,o2,p1,o0,p2,o1,p0,o0|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "R' D' L2 D R F2 U R2 D' R2 U' F2 L2 U R2 D R2"
  ],
  [
    "ZC:p3,o2,p1,o0,p2,o0,p0,o1|ZE:p2,o0,p1,o0,p0,o0,p3,o0",
    "R F' B' U2 F B' R B2 R2 U2 R B2 R2 B2 U2 R U2 R"
  ],
  [
    "ZC:p3,o0,p1,o2,p2,o1,p0,o0|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U L' B2 L' F2 L B2 L' F2 L2"
  ],
  [
    "ZC:p3,o2,p1,o1,p2,o1,p0,o2|ZE:p3,o0,p1,o0,p2,o0,p0,o0",
    "L U2 L2 U' L U R' U2 R U2 L2 U2 L U2 B2 L2 B2 U2"
  ],
  [
    "ZC:p3,o0,p2,o2,p0,o0,p1,o1|ZE:p0,o0,p1,o0,p3,o0,p2,o0",
    "L D R2 D' L U2 L2 B2 U' L2 U' F2 L2 U B2 U2"
  ],
  [
    "ZC:p3,o2,p2,o1,p0,o1,p1,o2|ZE:p0,o0,p2,o0,p1,o0,p3,o0",
    "R2 B2 D' L2 U B2 U' L' U2 R D2 L' B2 U2 R' B2 R U2 R"
  ],
  [
    "ZC:p3,o0,p2,o1,p0,o0,p1,o2|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "F' D' B2 D F' D' B2 L2 U L2 F2 D R2 U' R2 U'"
  ],
  [
    "ZC:p3,o0,p2,o1,p0,o2,p1,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "U' L2 U' L2 D F2 R2 U R2 B2 D' F' D B2 D' F'"
  ],
  [
    "ZC:p3,o1,p2,o0,p0,o1,p1,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R' F B' R F' B R' F' U2 F U2 F2 R2 F' U2 F R2 F2 R2"
  ],
  [
    "ZC:p3,o1,p2,o2,p0,o0,p1,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "R L' U2 R L F L2 B D2 B' L2 U2 F' U2 F' R2 F2"
  ],
  [
    "ZC:p3,o2,p2,o0,p0,o0,p1,o1|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "U L2 U L2 D' B2 R2 U' R2 F2 D B D' F2 D B"
  ],
  [
    "ZC:p3,o2,p2,o0,p0,o1,p1,o0|ZE:p0,o0,p3,o0,p2,o0,p1,o0",
    "B D F2 D' B D F2 L2 U' L2 B2 D' R2 U R2 U"
  ],
  [
    "ZC:p3,o0,p2,o0,p0,o2,p1,o1|ZE:p1,o0,p2,o0,p3,o0,p0,o0",
    "U F' L2 F' R2 F L2 F' R2 F2 U2"
  ],
  [
    "ZC:p3,o1,p2,o2,p0,o0,p1,o0|ZE:p1,o0,p3,o0,p0,o0,p2,o0",
    "F2 U' L2 F2 L2 U' L2 F U2 F' U2 F2 L2 F U2 F' U2 F"
  ],
  [
    "ZC:p3,o0,p2,o2,p0,o2,p1,o2|ZE:p2,o0,p0,o0,p3,o0,p1,o0",
    "B' U2 R2 U' F' U' B2 U2 R2 F D2 R2 B2 R2 B' D2 B'"
  ],
  [
    "ZC:p3,o1,p2,o2,p0,o0,p1,o0|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "B2 U L2 B2 L2 U L2 F' L2 F U2 B2 L2 F' L2 F U2 B'"
  ],
  [
    "ZC:p3,o2,p2,o1,p0,o0,p1,o0|ZE:p2,o0,p3,o0,p1,o0,p0,o0",
    "L2 U' F2 L2 F2 U' R2 B2 R' B2 L B2 D2 L D2 R' B2 L"
  ],
  [
    "ZC:p3,o0,p2,o0,p0,o1,p1,o2|ZE:p3,o0,p0,o0,p1,o0,p2,o0",
    "U L2 F2 L B2 L' F2 L B2 L"
  ],
  [
    "ZC:p3,o2,p2,o2,p0,o1,p1,o1|ZE:p3,o0,p2,o0,p0,o0,p1,o0",
    "F U2 F2 U' F U F L2 F2 L2 F U2 F' U2 L2 F2 L2"
  ],
  [
    "ZC:p3,o1,p2,o2,p1,o1,p0,o2|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "R2 U F2 R2 F2 U F2 R2 F R2 F R2 U2 R2 F' R2 F R2"
  ],
  [
    "ZC:p3,o2,p2,o0,p1,o0,p0,o1|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "F R2 U R2 U F2 L2 D2 F B L2 U2 B2 U2 B'"
  ],
  [
    "ZC:p3,o2,p2,o1,p1,o2,p0,o1|ZE:p0,o0,p2,o0,p3,o0,p1,o0",
    "R2 U F2 R2 F2 U R D2 L' U2 B2 U2 L D2 R F2 U2"
  ],
  [
    "ZC:p3,o1,p2,o2,p1,o0,p0,o0|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "R B2 U B2 U R2 F2 D2 R L F2 U2 L2 U2 L' U2"
  ],
  [
    "ZC:p3,o1,p2,o2,p1,o1,p0,o2|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "B2 U R2 F2 L2 D F D2 F R2 U2 R2 F' D2 F R2 U2"
  ],
  [
    "ZC:p3,o2,p2,o1,p1,o2,p0,o1|ZE:p0,o0,p3,o0,p1,o0,p2,o0",
    "L2 U' F2 R2 B2 D' R' D2 R' F2 U2 F2 R D2 R' F2"
  ],
  [
    "ZC:p3,o1,p2,o2,p1,o1,p0,o2|ZE:p1,o0,p2,o0,p0,o0,p3,o0",
    "F2 U R2 F2 R2 U F D2 B' D2 R2 D2 B D2 F R2 U2"
  ],
  [
    "ZC:p3,o0,p2,o1,p1,o2,p0,o0|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "B L2 U L2 U F2 R2 D2 F' B' R2 U2 B2 U2 F'"
  ],
  [
    "ZC:p3,o1,p2,o2,p1,o1,p0,o2|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "F2 U' R2 F2 R2 U' F' D2 B U2 L2 U2 B' D2 F' R2"
  ],
  [
    "ZC:p3,o2,p2,o1,p1,o2,p0,o1|ZE:p1,o0,p3,o0,p2,o0,p0,o0",
    "F2 U' R2 B2 L2 D' R2 F2 L D2 L F2 U2 F2 L' D2 L F2"
  ],
  [
    "ZC:p3,o0,p2,o0,p1,o1,p0,o2|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "L F2 U F2 U R2 B2 D2 R' L' B2 U2 L2 U2 R' U2"
  ],
  [
    "ZC:p3,o1,p2,o2,p1,o1,p0,o2|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "F2 U R2 F2 R2 U F' D2 B U2 L2 U2 B' D2 F' R2"
  ],
  [
    "ZC:p3,o2,p2,o1,p1,o2,p0,o1|ZE:p3,o0,p0,o0,p2,o0,p1,o0",
    "R2 U' F2 R2 F2 U' R D2 L' U2 B2 U2 L D2 R F2 U2"
  ],
  [
    "ZC:p3,o2,p2,o1,p1,o2,p0,o1|ZE:p3,o0,p1,o0,p0,o0,p2,o0",
    "F2 U' R2 F2 R2 U' R2 F2 R B2 L D2 F2 D2 L' B2 R F2"
  ]
]);
